import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import type { Metadata } from 'next'
import "./global.css"
import ThemeRegistry from '@/lib/components/ThemeRegistry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </ThemeRegistry>
    </html>
  )
}